### get all students
GET http://localhost:3000/students

### get student by id

Get http://localhost:3000/students/64d08ae7acdf96497386e275




### Create student
POST http://localhost:3000/students HTTP/1.1
content-type: application/json

{
  "year": 2000,
  "semester":"Fall-20",
  "profile": {
    "name": "Joseph",
    "phone": "0800 999111222",
    "address": "Global Village"
  },
  "courses": ["MATH 111X", "MATH 250"]
}

### update student
PUT http://localhost:3000/students/64d0b60815d5c51b4f8e3ebf
content-type: application/json

{
  "year": 2022,
  "semester":"Fall-22",
  "profile": {
    "name": "Hary",
    "phone": "0900 8881111",
    "address": "Washington"
  },
  "courses": ["HUM 101", "MATH 109"]
}

### delete student
DELETE http://localhost:3000/students/64d0ac68e713e0a9bb86a495