// LOCALHOST
### Get all students
GET http://localhost:8080/students

### Create contact
POST http://localhost:8080/students HTTP/1.1
content-type: application/json

{
  "firstName": "Maryam",
  "lastName":"Waheed",
  "dob": "06/05/2016",
  "mobile": "0321 999 2222",
  "email": "maryam@fake.com",
  "address": "Gulberg Green",
  "city": "Islamabad",
  "country": "Pakistan"
}
### Create contact
POST http://localhost:8080/courses HTTP/1.1
content-type: application/json

{
  "enrolledYear": "2022",
  "enrolledDegree": "BS",
  "major": "Business Management",
  "registeredCourses": "MG100, MTH107",
  "collegeName": "School of Managemnet Sciences"
}





// PRODUCTION Deploy
### Get all contacts
GET https://lesson4-swagger.onrender.com/contacts


### Create contact
POST https://lesson4-swagger.onrender.com/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Ibrahim",
  "lastName":"Waheed",
  "dob": "05/06/2017",
  "mobile": "0321 111 2222",
  "email": "ibrahim@fake.com",
  "address": "Gulberg Green",
  "city": "Islamabad",
  "country": "Pakistan"
}
